#include "+A.h"




void +A::+perimeter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--107-1--1ad97b95:16deecdb47e:-8000:0000000000001789 begin
{
}
// section -64--88--107-1--1ad97b95:16deecdb47e:-8000:0000000000001789 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void +A::+aire(void  a)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--107-1--1ad97b95:16deecdb47e:-8000:000000000000178B begin
{
}
// section -64--88--107-1--1ad97b95:16deecdb47e:-8000:000000000000178B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
